### ISSUE TITLE
Publish pylutron on pypi

### ISSUE THREAD

**Issue by andrey-git** [thecynic/pylutron#3]
Could you publish this package on Pypi, so it can be fetched without specifying the github URL?

home-assistant/home-assistant#7069

**Comment by thecynic** [comment]
Done. https://pypi.python.org/pypi?name=pylutron&version=0.1.0&:action=display

**Comment by thecynic** [comment]
PR https://github.com/home-assistant/home-assistant/pull/7664 for HASS
