### ISSUE TITLE
Project seems to be unmaintained

### ISSUE THREAD

**Issue by cdheiser** [thecynic/pylutron#31]
Including @jon102034050 and @nickovs as interested parties.

This project appears to no longer be maintained.  It's been over 6 months since the last commit, and it's been almost a year since the last version was released to PyPi.

Several contributors (including myself) have expressed interest in actively maintaining and contributing to this project, and would be preferred over forking the project.  There are multiple outstanding pull requests queued up and several of us would like to make continued improvements to the Lutron integrations in home assistant which depends on this library.

**Comment by dummptyhummpty** [comment]
@cdheiser I’d be interested in helping out in anyway possible. I don’t know Python, but would love to learn. I currently have a RadioRA2 repeater and Pico remote, until I can afford the rest of the components for my house.

**Comment by JonGilmore** [comment]
@thecynic - just bumping this up, any chance you can make @cdheiser a maintainer so we can push some PR's through?

**Comment by nickovs** [comment]
@cdheiser and @JonGilmore If there continues to be no reply we might want to consider doing the fork, renaming to pylutron2, pushing it to PyPI under the new name and then sending a PR to HomeAssistant to change over to the new version.

**Comment by JonGilmore** [comment]
I'm all in favor of it. Pretty sure the original maintainer has fallen off the face of this planet :(

**Comment by thecynic** [comment]
Sorry, I'm still alive. Just have had family and work commitments really
take over whatever free time I have. I've also had some health issues I had
to work through.

I'll try to go through the backlog here in the next week or two. If I still
can't, I'll designate someone else to have write access to the repo.

Dima

**Comment by JonGilmore** [comment]
Thanks for replying Dima, glad you're doing OK - health is important! Let us know how any of us can help with this project!

**Comment by avpavp** [comment]
Hey @thecynic,

I'm sure we all understand being too busy (I certainly can)...

It might be time to let someone else help here...?

Thanks for you work!

**Comment by JonGilmore** [comment]
hey @thecynic - any updates? Hope you're doing well. Is it possible to maybe add myself, @cdheiser, and @nickovs as maintainers and we can help collab to push existing PR's through??

**Comment by thecynic** [comment]
I think I just worked through the backlog of PRs at least. Hopefully once they all get updated and merged, I'll rev the version and push a new copy to pipi.

**Comment by JonGilmore** [comment]
@thecynic any chance you can push the new updates to PyPI? These upstream changes would help facilitate changes I'm proposing in Home Assistant..

**Comment by bdunks** [comment]
@thecynic bumping the request to publish to PyPI. There were some very helpful capabilities added to the library over the last 13 months.

**Comment by JonGilmore** [comment]
@nickovs @bdunks @cdheiser @dummptyhummpty  @avpavp @Tuckie 
Does anybody have feelings if we just dump @thecynic and just fork and handle it on our own? I feel like this is going nowhere are this point, and it's very clear that he's not going to give access up.

**Comment by dummptyhummpty** [comment]
@JonGilmore While I understand that @thecynic is busy with life, and I think there's been a good effort to keep him involved, but I agree that we need to fork at this point. We can always merge back later if needed.

**Comment by thecynic** [comment]
Added @JonGilmore as contributor.

**Comment by dummptyhummpty** [comment]
@thecynic Thank you for doing that!

**Comment by thecynic** [comment]
Now how to share pypi upload access.

**Comment by JonGilmore** [comment]
Sweet, thanks @thecynic - I've got an account on PyPI, but how are you currently pushing to PyPI?

**Comment by nickovs** [comment]
@thecynic You need to log in to PyPI.org, go to 'Your projects', select 'Manage' on the PyLutron project and go to the 'Collaborators' tab. You will need @JonGilmore 's PyPI user name and from there you can add him either as a Maintainer (in which case he can just push releases) or as a co-owner (in which case he can add new collaborators and delete old releases).

**Comment by JonGilmore** [comment]
Thanks @nickovs ! @thecynic can you please add @nickovs and @cdheiser as contributors? I spent quite a bit of time in python, but don't do it full time, so I still have quite a bit to learn. Might be good to have some seasoned vets in place to help out. 
FWIW Dima, I'm `JonGilmore` on PyPI as well.

**Comment by thecynic** [comment]
I added cdheiser to contributors in case I'm not responsive again.

Gonna try better to keep up with things, at least once every few days. Let's see how this goes. I'll close the issue for now, feel free to reopen if things get bad.
