### ISSUE TITLE
led / component number calculation

### ISSUE THREAD

**Issue by JonGilmore** [thecynic/pylutron#35]
https://github.com/thecynic/pylutron/blob/master/pylutron/__init__.py#L282
When `led_num` is calculated from the component number, it assumes that the led number is 80 less than the component number. For the case of the `MAIN_REPEATER` device type, this is not true. Here's a snippet of the LED `ComponentNumber` from my XML: 
```
                          </Preset>
                        </Presets>
                      </Action>
                    </Actions>
                    <Notes />
                  </Button>
                </Component>
                <Component ComponentNumber="101" ComponentType="LED">
                  <LED UUID="133" isReverseLogic="false" ProgrammingModelID="957" />
                </Component>
                <Component ComponentNumber="102" ComponentType="LED">
                  <LED UUID="134" isReverseLogic="false" ProgrammingModelID="9441" />
                </Component>
```
I think we need to do a check to see if we're looking at a `MAIN_REPEATER` device type, and if so, subtract 100 instead of 80. Thoughts? 
CC @thecynic

**Comment by thecynic** [comment]
Yeah, you are right. For main repeater its 100, for other keypads its 80. I'll see if i can spin a patch.
