### ISSUE TITLE
PyPI update?

### ISSUE THREAD

**Issue by JonGilmore** [thecynic/pylutron#37]
@thecynic can we get an update pushed to PyPI? It'd be awesome to see all this hard work get realized in homeassistant :D

Thanks for all the hard work on this btw!

**Comment by thecynic** [comment]
Yes, I'd like to get the connectivity stuff reviewed and then i'll push it. I'd also like to push the occupancy group stuff, waiting for achatham to re-review.

I guess i can just push tip, no harm in pushing.

**Comment by JonGilmore** [comment]
Totally understand ;) 
Thx

**Comment by thecynic** [comment]
Done, pushed tip as 0.2.1. Will push 0.2.2 once the next few PRs go in.
