### ISSUE TITLE
Are Pico remotes supported?

### ISSUE THREAD

**Issue by dummptyhummpty** [thecynic/pylutron#43]
If not, I would love to see support for the Pico remotes.

Thanks for all of the work that is being done on this.

**Comment by cdheiser** [comment]
Yes.  Pico Remotes are accessible like any other keypad.

**Comment by dummptyhummpty** [comment]
@cdheiser Awesome! Do you happen to know if they are exposed in HomeAssistant?

**Comment by cdheiser** [comment]
Yes, they should show up as scenes.

**Comment by JonGilmore** [comment]
@dummptyhummpty take at look at the docs, I updated with an example on how to catch the pico press and trigger an automation: https://www.home-assistant.io/integrations/lutron/#example-automations
