### ISSUE TITLE
Disconnects every few seconds from RadioRA2 main repeater

### ISSUE THREAD

**Issue by beavis9k** [thecynic/pylutron#49]
I first saw this in homeassistant after an update. The pylutron package was updated from 0.2.2 to 0.2.5 as part of that update.

The logs show "Disconnected" every few seconds, then pylutron reconnects to the main repeater. This causes HA to lose control and status of the lutron devices at random times. Sometimes a restart of HA will temporarily fix it. Eventually, the main repeater lights all change to and red and the repeater must be power cycled.

**Comment by beavis9k** [comment]
I've tracked the problem down to 693b1838a762a28648febab6a95fe96dff4aae6d. There are two things in that commit causing the issue. I'm testing a fix locally for a couple days before pushing to my fork of pylutron and making a PR.

**Comment by JonGilmore** [comment]
thanks @beavis9k - looking forward to seeing your PR. Have you checked out https://github.com/thecynic/pylutron/pull/48 or https://github.com/thecynic/pylutron/issues/17?

**Comment by beavis9k** [comment]
No problem; I'm happy to help.

#17 should be pretty independent of what I'm doing, so no problem there. Turns out the TCP keepalive and keepidle are at the root of what's making my repeater to go into it's error state - my repeater doesn't seem to support either. I'm testing a different way of keeping the connection alive and detecting disconnects that hopefully works on all platforms and all repeater firmware versions, but I'm not a python guy so it might take a bit of time. I'll rebase and update as necessary if #48 makes it in before I'm ready with this.

**Comment by JonGilmore** [comment]
Sweet, looking forward to seeing that. So is it the repeaters that don't support the tcp keepalive/keepidle, or the host OS that is maintaining the connection?

**Comment by beavis9k** [comment]
It appears the repeater doesn't support it. According to tcpdump there are no responses to the packets sent by pylutron, so pylutron disconnects and reconnects every few seconds. I don't know if it's the keepalive/keepidle packets or the disconnects/reconnects that cause the repeater to lose it's mind, but ultimately that doesn't matter because the end result is the same.

If I'm the only one having this issue it's possible the changes in 693b1838a762a28648febab6a95fe96dff4aae6d are just fine. I'm running a pretty old repeater FW because my lutron contact went MIA a while ago. I still think it's worth a little more work to find a disconnect detection method that works for all platforms though.

**Comment by thecynic** [comment]
Sorry to hear that @beavis9k but I'd strongly advise you to upgrade repeater firmware :( You using inclusive or essential?

I don't think we should remove the keep alive stuff as it does solve quite a lot of other problems (though i guess it creates new ones :) ).

My best alternative would be to take an argument somewhere at creation time to not do keep alive (and plumb it to the home assistant config), but your experience will likely stink. If you happen to reboot the repeater, or your wifi cuts out and you are on wifi, etc. you'll have a world if pain.

Regarding "more work to support all platforms" is a bit of a stretch though. Your firmware is super old and clearly buggy, who knows what other issues you'll come across. Seems like more appropriate course of action is for you to figure out how to keep your firmware up-to-date.

**Comment by beavis9k** [comment]
@thecynic so you're not seeing this issue? What version of FW are you running on your main repeater?

**Comment by thecynic** [comment]
@beavis9k 
GNET> ?SYSTEM,8
OS Firmware Revision = 10.6.0 [Nov 01 2016 05:48:45]

**Comment by cdheiser** [comment]
@beavis9k is this still an issue for you?  I'll note I haven't seen problems like this in quite some time, and this issue is about 18 months old at this point.  Feel free to reopen.
