### ISSUE TITLE
Slow pylutron initialization right after project transfer from RR2 Essentials

### ISSUE THREAD

**Issue by richsands** [thecynic/pylutron#60]
Hi - running RR2 Essentials 12.7.0 and a RR2 repeater with 12.7 firmware update. 93 devices out of 100 configured. 63 repeater phantom buttons configured. I also have a Connect Hub. So a big set-up, whole house. This is integrated with the latest HomeAssistant 0.113.3 running on an Intel NUC under Proxmox / HassOS 4.12, using the current stock HA Lutron RR2 integration. All of this works terrific - I have fine-grained control over the whole house lighting.

My issue: if I transfer my project to the repeater, and have Essentials still open under Windows or very recently closed, when I restart HA to reload the integration with the repeater, the HA integration takes over 10 minutes to initialize. It always finishes successfully, but it takes a long time. If I have logging set to something below "error" for pylutron, I see the "Disconnected" warning over 40,000 times - it logs it many times per second. If I have logging set to "error" then I don't see all those messages but it still takes a long time so I assume some problem is still going on behind the scenes.

If I wait a few minutes after the transfer completes successfully, or if the repeater has been running normally for awhile, initialization takes about 23 seconds and I do not see all the "Disconnected" messages in the log.

This problem started about a month ago when I added all the phantom button programming, but it may be a coincidence with other changes - hard to tell. I migrated to the NUC from a RPi around that time also as the RPi couldn't gracefully handle my growing HA config.

Other than this, everything is working perfectly and I am very happy with performance and reliability. I have elaborate scenes to shift lighting around, and they operate silky smooth with Lutron's ClearConnect.

From reading your issue tracker I can see you're actively updating this project and planning an overhaul of the HA Lutron integration to go with a new version. I thought you'd want to know about this odd behavior right after a transfer. When debugging all of this, I often adjust the project, transfer it, and then fiddle with HA's configuration to make things work, so it is a common work flow to reboot HA right after a transfer. Has anyone else run into this sort of issue?

**Comment by cdheiser** [comment]
I have observed this behavior and believe it's related to the 12.x series
firmware.  Something about it makes the telnet server not respond for about
10 minutes after an update.  Or it will work fine if you power cycle the
main repeater.

**Comment by richsands** [comment]
Whew glad I'm not crazy and it isn't just me. Might have to install a NON-LUTRON smart plug to make power cycling happen.. LOL. I just tried it again and looked at the repeater after finishing the transfer, and the usual flashing red LED pattern during transfer continues after finished for 10 minutes, and then goes to normal. I see someone else reported this at forums.lutron.com but without enough detail for Lutron to respond intelligently. I will report it there, now. Could pylutron detect this and report a warning diagnostic so users (like me) aren't baffled? Weird.

**Comment by thecynic** [comment]
I'm not sure how pylutron would detect this vs just a host that isn't
there? It'll try to reconnect continuously every few seconds. Not sure how
you can get hass to know the reasons why. Presumably as you looked at the
log, you'd see it reconnecting?

I'm still running super old firmware so I don't see these problems :)
Personally, I got everything working with Lutron and decided not to keep
messing with it as I don't really have any major bugs that I needed to
chase. I'll probably update at some point though.

**Comment by richsands** [comment]
I haven't poked more at it but if it is refusing the connection rather than timing out, that might be a simple way to detect this. I suspect it might be doing that, as the pylutron code seems to try over and over very rapidly, logging all the failed attempts with "disconnected" rather than trying and waiting and timing out and trying again. hass could know why if the lutron integration flipped a binary sensor or did something else hass can react to if this condition exists. I haven't thought that through either but I bet there is some dead-simple thing an integration can do to signal "I'm broken for reason X" that automations could react to. I reported it on the lutron forums. Let's see if they fix it in a future firmware update. I don't see this as a huge problem but it is an annoyance. If with a few lines of code, pylutron could report something sensible in the log and stop trying for awhile that would be an improvement. If it could report something hass could react to, that would be a big improvement. The fix for the underlying problem is probably up to Lutron, though.

**Comment by richsands** [comment]
As an aside (not that anyone but me cares...) the reason I am updating to new firmware is that I bought a whole lot of the new RRD-PRO dimmers. These aren't adaptive like the 6NA dimmers - you have to set forward or reverse phase in the Essentials software when you configure the project. The new PRO dimmers are a lot less expensive as they do away with the "smart" phase sensing hardware in the dimmers. I saved over $1000 with them. They're also a lot more reliable, in that the phase sensing can get confused if different LED drivers are attached to the same circuit - a tape light plus recessed lights for a mantel, for instance. It is better to tell the dimmer what to do rather than rely on the phase detecting stuff in the 6NA. To use the new PRO dimmer requires new firmware.

**Comment by cdheiser** [comment]
Can you include a link to the lutron post?

**Comment by richsands** [comment]
https://forums.lutron.com/showthread.php/16014-Problem-with-RR2-Telnet-integration-after-transfer?p=37644&viewfull=1#post37644 no reply yet.

**Comment by richsands** [comment]
YAY! Finally got around to installing RR2 12.8.0 and associated repeater firmware 12.8 update. This problem has been fixed by Lutron - the repeater immediately returns to normal operating mode when transfer is complete. Maddening they don't acknowledge bugs, nor have firmware release notes, but at least they fixed it.
