### ISSUE TITLE
Is Lutron training required/what level to use this package?

### ISSUE THREAD

**Issue by EricE** [thecynic/pylutron#62]
I have gone through the online training and have the Essentials SW.  I designed a system for a new house last year and with all the COVID delays it is just getting to near the end of the project.  I hopefully figured this out a while back but will I have any limitations with using this package (I'm using Home Assistant) since I don't have Essentials PC or Inclusive?  I didn't even recall that there was a Essentials PC, I thought I was going to be able to hook up and download into the controller so now I'm paranoid...

**Comment by cdheiser** [comment]
This doesn't run anything in the controller or in the lutron hardware at
all.  This is simply a library used by home assistant to talk to the Lutron
controller via the published APIs (over telnet).
