### ISSUE TITLE
Grafikeye QS with network interface support

### ISSUE THREAD

**Issue by Gorr75** [thecynic/pylutron#64]
Hi,
I have been looking to integrate my Grafikeye QS with a network interface https://www.lutron.com/TechnicalDocumentLibrary/040249.pdf into home assitant.
Is it possible to expand pylutron to support this? I would help testing it on my system. I have 2 grafik eye qs and 3 International seeTouch QS 10-Button Wallstation with Raise/Lower
Thank you in advance!
Not sure if it's ok to post here but I couldn't find any good info on the HA community pages. Also posted a similar post there.

**Comment by cdheiser** [comment]
Have you just tried it?  If Grafikeye QS truly uses the same integration
protocol, I'm not sure why it wouldn't just work already.   The only thing
I could think of that might get in the way is the device type might be
different for your keypads and thus might need to be added.

**Comment by Gorr75** [comment]
I haven't tried it since I think it will fail but I will give it a try this weekend. 
Grafikeye QS not asking for any password just the user which is defaults to nwk

This is from a home assistant post I did.

"I have a Grafikeye QS that have a IP interface that I think is the same commands as homeworks QS. How ever there is only a login and no password and prompt is blank as in no QNT> just

Using putty on port 23 I get this login screen:
login: with one space after :
When I enter my login default nwk I get this prompt:

connection establised
on the line under just a blank

I have had a look at https://github.com/home-assistant/core/pull/9121/commits/efe7a5580d7bdc0e36cfd06ea8641f36d8a8745c without any success.

I have this LUA script that works:

local socket = require “socket”
local lutron_tcp

function connectLutron()
lutron_tcp = assert(socket.tcp())
lutron_tcp:settimeout(0.5)
lutron_tcp:connect(“192.168.5.212”, 23)
end

function sendLutron(cmd)
lutron_tcp:send(cmd … “\r”)
sleepLutron()
end

function disconnectLutron()
lutron_tcp:close()
end

function sleepLutron()
luup.sleep(500)
end

function powerOnLutron()
sendLutron(“password”)
sleepLutron()
end

connectLutron()
powerOnLutron()
sendLutron("#DEVICE,0x000b0eb9,3,14,30,1")
disconnectLutron()

Thanks in advance!

**Comment by cdheiser** [comment]
@Gorr75 did you try it?  From looking at the code, even if your prompt is different, this code will just wait 3 seconds before moving on anyway if it doesn't see GNET>.  

I'm going to assume it just works.  If it doesn't, then we'd be happy to review and accept a PR to fix the code, but as I don't have a standalone Grafikeye QS, I don't have a way to test this myself.
