### ISSUE TITLE
pypi repo secret api token

### ISSUE THREAD

**Issue by JonGilmore** [thecynic/pylutron#68]
@thecynic I'd like to automate the PyPI github release with github actions upon a repo tag, but I'll need to either be able to create the secret on this repo for my PyPI API token (requires repo admin), or if you could add your repo token, I'd _really_ appreciate it! 

Thanks!

**Comment by JonGilmore** [comment]
@thecynic would you mind giving this a look? I'd like to merge in https://github.com/thecynic/pylutron/pull/69 but need this first. Thanks!!

**Comment by thecynic** [comment]
Yeah, let me go figure out how to do that.

**Comment by thecynic** [comment]
created PYPI_PASSWORD secret with an access token to upload packages for pylutron on PyPi. Give it a go?

**Comment by JonGilmore** [comment]
[Looks good](https://pypi.org/project/pylutron/0.2.9/) - [here's the workflow](https://github.com/thecynic/pylutron/runs/3091000135?check_suite_focus=true)! Thanks for adding the repo secret @thecynic
