### ISSUE TITLE
Would this work with RF Dimming Module (lmj-5t-dv-b rf)

### ISSUE THREAD

**Issue by ericlegallais** [thecynic/pylutron#76]
I'd like to know if pylutron would/will work with a dimming module lmj-5t-dv-b rf? I can't test it right now, but I'd used the modules to control some 0-10v drivers (a total of 16) and before buying them I'd like to know if it's going to work.

Thanks a lot for the good work btw, already using this integrated with Home Assistant and Lutron keypads

**Comment by cdheiser** [comment]
It should work fine.  If it doesn't, we can fix it with a little debugging
data from you.  In theory, this should just present like any other summer.

**Comment by ericlegallais** [comment]
Excellent news. I'll buy them, test them and tell you guys if it's not working. CLosing issue. :)
