### ISSUE TITLE
Lutron illumination

### ISSUE THREAD

**Issue by kaaspad** [thecynic/pylutron#79]
Hi I'm running a lutron system that's older than the QS version - its running the Lutron illumination software. I have ethernet access to the controller. Do you know if pylutron or any of the HA integrations (lutron or homeworks) will work with this system? If so which one and how would I start. Thanks!

**Comment by cdheiser** [comment]
The integration protocol guide only mentions HomeWorks QS.  I don't see any
mention of HomeWorks Illumination in the protocol guide, nor can I find an
integration guide for HomeWorks Illumination.  So I'm going to guess that
none of the home assistant lutron integrations are going to work.  If you
can telnet and login to your system, then you can try the lutron
integration which uses pylutron.

**Comment by kaaspad** [comment]
Thanks for responding, I can both telnet and login. I’ll try to install the Lutron one and see what happens. Thanks
