### ISSUE TITLE
Support for new Caseta switches

### ISSUE THREAD

**Issue by tal** [thecynic/pylutron#80]
I just installed one of the new Caseta Diva switches and it doesn't appear to be supported. I am using this via Home Assistant and am not setup to easily debug this directly, but I was curious if this was an expected issue or the library _should_ be able to handle new switches and something else may be going on.

Thanks!

**Comment by JonGilmore** [comment]
pylutron isn't compatible with ra3. You should check out this [repo here](https://github.com/gurumitts/pylutron-caseta/issues/115)
