### ISSUE TITLE
GRAFIK_T_HYBRID_KEYPAD unsupported

### ISSUE THREAD

**Issue by moonfall** [thecynic/pylutron#81]
Hi,

I was wondering if it would be possible to add support for GRAFIK_T_HYBRID_KEYPAD?  I included a sample xml fragment from the xml.

I'm not sure if anything is required besides changing _parse_area() -- if that's it and it would make your life easier I can submit a pull request.

[keypad.txt](https://github.com/thecynic/pylutron/files/10243336/keypad.txt)

**Comment by cdheiser** [comment]
You're probably right.  You want to try a modified version and see if it
works with your setup and submit a pull request if it does?

**Comment by moonfall** [comment]
Is it possible to get a release so this can get incorporated into a new HA?

**Comment by cdheiser** [comment]
Let's see if I can get this to publish to PyPi
