### ISSUE TITLE
NON_DIM_INC is also a switch, not a light

### ISSUE THREAD

**Issue by wkearney99** [thecynic/pylutron#83]
It's possible to use some of the Lutron devices that have dimmers as switches.  They show up in the DbXmlInfo.xml file as having an OutputType of "NON_DIM_INC".

The code in https://github.com/thecynic/pylutron/blob/master/pylutron/__init__.py needs to be changed to reflect that.

This is a list of the various OutputTypes from one site here:

OutputType="AUTO_DETECT"
OutputType="CCO_MAINTAINED"
OutputType="CEILING_FAN_TYPE"
OutputType="INC"
OutputType="NON_DIM"
OutputType="NON_DIM_ELV"
OutputType="NON_DIM_INC"
OutputType="EXHAUST_FAN_TYPE"
OutputType="RELAY_LIGHTING"

The 12.9.0 version of Ra2 software lists several ways for a dimmer device to support a non-dimmed load (and that affects the XML output)

![image](https://user-images.githubusercontent.com/232313/209585007-9d56110c-df75-45b6-89e6-d1c1244168d2.png)

Unfortunately I don't have a site running from which I could export devices with all of the types.  But it'd be a safe starting point to assume 'starts with "NON_DIM" would be a more versatile comparison instead of just 

752    return self.type != 'NON_DIM' and not self.type.startswith('CCO_')

Could it be as easy as just changing that to:

return( self.type not in ('NON_DIM', 'NON_DIM_INC', 'NON_DIM_ELV', 'EXHAUST_FAN_TYPE', 'RELAY_LIGHTING') and (not self.type.startswith('CCO_')) )

**Comment by grstreten** [comment]
This is fixed and can be closed :)
